<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/9_Regresion_Logistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#Cargar archivo csv
df= pd.read_csv("DataAnalytics.csv")
df.head()

Administrador  Usuario  botón correcto  tiempo de interacción mini juego  \
0       nicolas  nicolas             1.0               5.399169   Despegue   
1       nicolas  nicolas             0.0               1.283400   Despegue   
2       nicolas  nicolas             1.0               2.700226   Despegue   
3       nicolas  nicolas             0.0               3.050262   Despegue   
4       nicolas  nicolas             0.0               4.750256   Despegue   

   número de interacción color presionado  dificultad             fecha  \
0                    1.0             blue  Episodio 1  25/01/2024 09:26   
1                    2.0           violet  Episodio 1  25/01/2024 09:26   
2                    3.0            green  Episodio 1  25/01/2024 09:26   
3                    4.0            green  Episodio 1  25/01/2024 09:26   
4                    5.0            green  Episodio 1  25/01/2024 09:26   

   Juego  auto push  tiempo de lección  tiempo de sesión  
0  Astro        0.0                0.0               0.0  
1  Astro        0.0                0.0               0.0  
2  Astro        0.0                0.0               0.0  
3  Astro        0.0                0.0               0.0  
4  Astro        0.0                0.0               0.0

In [3]:
#Rellenamos nulos
df =df.fillna(method="bfill")
df =df.fillna(method="ffill")


C:\Users\vbece\AppData\Local\Temp\ipykernel_15928\374832835.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method="bfill")
C:\Users\vbece\AppData\Local\Temp\ipykernel_15928\374832835.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method="ffill")


In [4]:
#Analizar categorias de una columna
Categorias_Juego = df.groupby(['Juego'])['Juego'].count()
Categorias_Juego

Juego
Astro      3799
Cadetes    2066
Name: Juego, dtype: int64

In [5]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df[['número de interacción']]
Var_Dep= df['Juego']

In [6]:
#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

In [7]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [8]:
#Se escalan todos los datos
escalar = StandardScaler()

In [9]:
#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [10]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [11]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [12]:
#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

array(['Astro', 'Astro', 'Astro', ..., 'Astro', 'Astro', 'Astro'],
      shape=(1760,), dtype=object)

In [13]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[1128    0]
 [ 632    0]]


In [14]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Astro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.6409090909090909


In [15]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.6409090909090909


In [16]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Cadetes")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.0


In [17]:
# el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajef1 = f1_score(y_test, y_pred, average="binary", pos_label="Astro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.7811634349030471


***Método 1 Reponderación de las Clases***

In [18]:
#Reponderación de las clases
algoritmo_Pond = LogisticRegression(class_weight='balanced')
algoritmo_Pond.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [19]:
#Realizamos una predicción
y_pred_pond = algoritmo_Pond.predict(X_test) 
y_pred_pond

array(['Cadetes', 'Cadetes', 'Astro', ..., 'Cadetes', 'Cadetes',
       'Cadetes'], shape=(1760,), dtype=object)

In [20]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_pond)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[379 749]
 [148 484]]


In [21]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="Cadetes")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.39253852392538524


In [22]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred_pond)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.4903409090909091


In [23]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="Astro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.33599290780141844


***Método 2 Submuestreo o Sobremuestreo***

In [24]:
#%pip install imblearn

In [25]:
#Aplicamos la técnica de sobremuestreo (oversampling)
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

In [26]:
#Entrenamos el modelo sobremuestreado
algoritmo_Over_sampling = LogisticRegression()
algoritmo_Over_sampling.fit(X_resampled, y_resampled)

LogisticRegression()

In [27]:
#Realizamos una predicción
y_pred_over_sampling = algoritmo_Over_sampling.predict(X_test) 
y_pred_over_sampling

array(['Cadetes', 'Cadetes', 'Astro', ..., 'Cadetes', 'Cadetes',
       'Cadetes'], shape=(1760,), dtype=object)

In [28]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[379 749]
 [148 484]]


In [29]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="Astro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.7191650853889943


In [30]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred_over_sampling)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.4903409090909091


In [31]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="Astro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.33599290780141844
